/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.ui;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import sistem.manager.BarangManager;
import sistem.model.BarangModel;
/**
 *
 * @author Rapiii
 */
public class CariBarang extends javax.swing.JFrame {
    
    private String sql;
    private PreparedStatement ps = null;
    /**
     * Creates new form CariBarang
     */
    public CariBarang() {
        initComponents();
        setLocationRelativeTo(null);//set lokasi frame di tengah layar
        initTableBarang(); 
        loadBarang("");
    }
    
    //Dekalrasi variable
    public static DefaultTableModel tableModel;
    public static List<BarangModel> listBarangModel;
    
    public void initTableBarang() {
        //Deklarasi array bookColumns tipe data String
        String[] barangColumns = new String[]{"Id Barang", "Nama Barang", "Tanggal Exp", "Jumlah", "Harga", "Kategori"};
        
        int[] columnWidth = {//Deklarasi array columWidth tipe data int
//            100, 100, 100, 100, 100, 100 //lebar tiap kolom
        };
        
        
        
        tableModel = new DefaultTableModel(barangColumns, 0);//Deklarasi tableModel 
        barangTabel.setModel(tableModel);//Set table model
        barangTabel.setRowHeight(20);//set jumlah baris table
        
        listBarangModel = new ArrayList<>();
        
        int i = 0;
        for (int width : columnWidth) {
            TableColumn column = barangTabel.getColumnModel().getColumn(i++);//set column bookTable
            column.setMaxWidth(width);//set lebar table
            column.setPreferredWidth(width);//set lebar table                
        }       
    }
    
    public static void loadBarang(String q){//Method untuk memuat data barang
        listBarangModel = new ArrayList<>();//Deklarasi arrayList
        listBarangModel = BarangManager.semuaBarang(q);//lalu nilainya adalah return nilai dari method semuaBarang
        tableModel.setRowCount(0);//set unutk jumlah baris menjadi 0
        listBarangModel.forEach(barangModel ->{//Melakukan perulangan untuk memasukkan data barang
                tableModel.addRow(new Object[]{
                    barangModel.getId_barang(),
                    barangModel.getNama_barang(),
                    barangModel.getExp_date(),
                    barangModel.getJumlah(),
                    barangModel.getHarga(),
                    barangModel.getKategori()
                });
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cariTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        barangTabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cari Barang");

        cariTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTxtActionPerformed(evt);
            }
        });
        cariTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariTxtKeyReleased(evt);
            }
        });

        barangTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Barang", "Nama Barang", "Tanggal Exp", "Jumlah ", "Harga", "Kategori"
            }
        ));
        barangTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(barangTabel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTxtActionPerformed

    private void cariTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTxtKeyPressed
        // TODO add your handling code here:
        ;
    }//GEN-LAST:event_cariTxtKeyPressed

    private void cariTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTxtKeyReleased
        // TODO add your handling code here:
        loadBarang(cariTxt.getText());
    }//GEN-LAST:event_cariTxtKeyReleased

    private void barangTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangTabelMouseClicked
        // TODO add your handling code here:
        Transaksi trs = new Transaksi();
        int i = barangTabel.getSelectedRow(); //mengambil data dari tabel
        TableModel tm = barangTabel.getModel();
        
        String id_barang = tm.getValueAt(i, 0).toString();
        String nama_barang = tm.getValueAt(i, 1).toString();
        String jumlah = tm.getValueAt(i, 3).toString();
        String harga = tm.getValueAt(i, 4).toString();
        
        trs.idBarang.setText(id_barang);
        trs.namaBarang.setText(nama_barang);
        trs.stokTxt.setText(jumlah);
        trs.hargaBrg.setText(harga);
        
        trs.setVisible(true);
        dispose();
    }//GEN-LAST:event_barangTabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable barangTabel;
    private javax.swing.JTextField cariTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
