/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.ui;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import sistem.helper.ConnectionHelper;

/**
 *
 * @author Rapiii
 */
public class TambahKonsumen extends javax.swing.JFrame {

    /**
     * Creates new form TambahKonsumen
     */
    //deklarasi variable
    String formtitle = "";
    int konsumenId = 0;
            
    public TambahKonsumen() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
    public TambahKonsumen(String title, int id){
        initComponents();
        setLocationRelativeTo(null);
        TmbhKonsumen.setText(title);
        formtitle = title;
        konsumenId = id;
        try {
            Connection conn = ConnectionHelper.getConnection(); //digunanakan untuk membangun koneksi
            Statement stm = conn.createStatement(); //digunakan untuk pengiriman statement SQL tanpa parameter, agar bisa melalukan query
            System.out.println(id);
            ResultSet rs = stm.executeQuery("SELECT * FROM pelanggan WHERE id_pelanggan = " + id); //Melalukan ExecuteQuery agar bisa mengambil data dari database lalu disimpan ke variabel rs atau ResultSet
            while (rs.next()) { //Melakukan iterable atau looping bila memiliki datanya di dalam database
                //menset data yang ditambahkann oleh  user
                namaKonsumen.setText(rs.getString("nama"));
                telpKonsumen.setText(rs.getString("no_telp"));
                almtKonsumen.setText(rs.getString("alamat"));
            }
        } catch (Exception e) {
            System.out.println("error" + e.getMessage());
        }
//        validateExite();       
    }
    
    //method unutk menampilkann informasi berhasil atau tidak menyimpan data buku
    public void showMessage(String message, int type){
        if(type == 1){
            JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, message, "Gagal", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    void updateKonsumen(int id) {
        try {
            Connection conn = ConnectionHelper.getConnection();
            Statement stm = conn.createStatement();
            String query = "UPDATE pelanggan SET nama = '" + namaKonsumen.getText() + "',"
                    + "no_telp = '" + telpKonsumen.getText() + "',"
                    + "alamat = '" + almtKonsumen.getText() + "' WHERE id_pelanggan = " + id + " ";

            stm.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data sudah di update ", "infomasi", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data tidak terupdate" + e.getMessage(), "infomasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    //method untuk menguhubungkan antara NB dengan localhost(database)
    void tambah(){
        try{
            Connection conn = ConnectionHelper.getConnection();
            Statement stm = conn.createStatement();
            String query = "INSERT INTO `pelanggan` (`nama`, `no_telp`, `alamat`) "
                    + "VALUES ('"+namaKonsumen.getText() +"', '"+ telpKonsumen.getText()+ "', '"+ almtKonsumen.getText()+
                    "');";
            
            stm.executeUpdate(query);
                    JOptionPane.showMessageDialog(null,"Data Sudah di Tambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch (Exception e){
             System.out.println(e);
        }
    }
    
    //method yang digunakan unutk close frame/windows
//    private void validateExite() {
//        TambahKonsumen.this.addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowClosing(WindowEvent e) {
//                super.windowClosing(e); 
//            }
//
//        });
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TmbhKonsumen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        telpKonsumen = new javax.swing.JTextField();
        almtKonsumen = new javax.swing.JTextField();
        namaKonsumen = new javax.swing.JTextField();
        canselBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        TmbhKonsumen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TmbhKonsumen.setForeground(new java.awt.Color(255, 255, 255));
        TmbhKonsumen.setText("Tambah Data Pelanggan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(TmbhKonsumen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TmbhKonsumen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Nama :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("No. Telp :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Alamat :");

        almtKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almtKonsumenActionPerformed(evt);
            }
        });

        namaKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKonsumenActionPerformed(evt);
            }
        });

        canselBtn.setBackground(new java.awt.Color(255, 0, 0));
        canselBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        canselBtn.setForeground(new java.awt.Color(255, 255, 255));
        canselBtn.setText("Batal");
        canselBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canselBtnActionPerformed(evt);
            }
        });

        submitBtn.setBackground(new java.awt.Color(0, 0, 255));
        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Simpan");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(almtKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telpKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canselBtn)
                .addGap(28, 28, 28)
                .addComponent(submitBtn)
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telpKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(almtKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canselBtn)
                    .addComponent(submitBtn))
                .addGap(0, 93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaKonsumenActionPerformed

    private void almtKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almtKonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almtKonsumenActionPerformed

    private void canselBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canselBtnActionPerformed
        // TODO add your handling code here:
        new DataPelanggan().setVisible(true);
        dispose();
    }//GEN-LAST:event_canselBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        if (konsumenId == 0) {
            tambah();
        } else {
            updateKonsumen(konsumenId);
        }
        new DataPelanggan().setVisible(true);
        dispose();
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahKonsumen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TmbhKonsumen;
    private javax.swing.JTextField almtKonsumen;
    private javax.swing.JButton canselBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namaKonsumen;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField telpKonsumen;
    // End of variables declaration//GEN-END:variables
}
